-- AlterTable
ALTER TABLE "latest_insights" ALTER COLUMN "r_p_1W" DROP NOT NULL,
ALTER COLUMN "r_p_1M" DROP NOT NULL,
ALTER COLUMN "r_MH" DROP NOT NULL,
ALTER COLUMN "r_WH" DROP NOT NULL,
ALTER COLUMN "o_MH" DROP NOT NULL,
ALTER COLUMN "o_WH" DROP NOT NULL,
ALTER COLUMN "o_ML" DROP NOT NULL,
ALTER COLUMN "o_WL" DROP NOT NULL;
